language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build

deploy:
  provider: heroku
  api_key:
    secure: M8HElDAespiWuZnNI3gjdnLv6zYVOVngSzi4ZGRmVypFKteUnqcBsv6Qi+6k6FVSbLp/bKg3DwQumQxHGR2LaHNsvCqJumGczTX+cMkR/OBDE3TciViJLnE4JiczQt6D7uEhbt5X5gN3STvqZM3n4LwKGv4nU6u7pyApKnDKkBPpTuuSJkeEGWhzuh9eUYFgNRpSlfTpgGqa+SRuRFTZzEFVTeMXiOD9+NrNtH/rLJFqXsL/iN6APuBKH+oCjpk+pzP7KH7oD7mO8x+YWvUOZPNSEHbLF5dH01OSKdqwaG4sCS8N/vMAJptKSvwKter2PruO+Xw8lI2s784/si5LpqKjrL2QFx+VikoHp0eQMN6i+NvBW/ypwuyF74Csxsq3WBMkODjGx5p337W4zu0pkPR0URj0o46GZKXqh67tkes/3n/Cxm2LrTROaaRwr0eT3uJGKR7MwhpVzLUQY1bvSiTEdbyvi7KIV+o3/OuCfKQsnKxtjxT1roUWE95c2zyE2jci2rONw0TWhJg7PeA4sdBK6m4VLNGhUnUMAUe+e7XbBPm0IJkIu5FvNIbvHo/4Pnz8mKpjLCWQxJrcRmbj1ptI97bkU7c3gq23bPPxOwdu7RBxoMb1dABf+RzHQF43dipUEtjrxG9IJO0TzxVrQ9/Pid/dZEqjA2/6Oj+d2v8=
  app: quigleysweb
  on:
    repo: mike-quigley/QuigleysWeb