language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: abzRgDGEZm3H/US2mNxdYfEsyU1yf5aIr7KxnAEq40kmJvidgMl2m3Uxn64sqAYktSBa5eMQBJMch5iEZwqMp1AOoB4N03Ncb8RvMt3V9EfSQpIgVEmTBBbriRdTOTEf9dSKmb/DI8zysbz2g0lM1GPwCtlBm5HXoDEC1dAA137q8txUNRIsVcPZy8V7P13eQrQlCfU3AtLOTljEiD8Z4U7XUp5bu0ruW2U4KU/JmPZe7OgUVG+aYlolISVCnuLqk3JQrX/Rd2PE1I8LJAhXNYQhE8styymSh96Lh4QtG+H1TIv/bNpsu/0Kk/R6B/O0DSzptDy/6Nf7+2EySMM3Rwa412Nqvm+73NwL2ZVLT4E2LzVshn9WEFRc32BwzMoMCv/v25RrjzavbfXlaNtyAe7+dMpDHCben6/3EQYZWGv3XQeUy7bOrSvHlIeLFC1/dmZpDZS8mq/gIKZio0FZ/X3FHTDTbQC6zSpF7ei1qTCYA/Ht5c8dZGvfqN7CaX/yIjmu2jNrVy4Ssvl5zq9Kw+P3Ev7ojGfsF8MO7HdiHS5cbPlpRXITE3TUnlUJKip8De/NDbCS8ohuv3EO++WRA27yQSCZMJjA5QKFlm4fEGURO4+VJRxoAkTuDCFUQGPkZC92v6kCzmeuDzL8ORy22p4OhGahLsuUpgPOBtH5PHY=
  app: quigleysweb
  on:
    repo: mike-quigley/QuigleysWeb
