language: node_js
node_js:
<<<<<<< HEAD
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
=======
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
>>>>>>> 8de3c33cbd9aad65874baa54b0befc3bd9a06a97

deploy:
  provider: heroku
  api_key:
<<<<<<< HEAD
    secure: tRvBc6YkQwWJ26mDs/jDoGqU70depbJKx+cphdGyF/E1HWXDo46cr+6Ib1jy6T47qZeLsZQwU7cxMRseTJ6kcOk2e+rqjOixb5CpveXvWw4DS4xRAoNqe0Hmd3P0OAo7LqJ2HA3msk3eRW8bzlkMfAlzY9vnirJcwSotv7usYARgCY4cakeLCf0+w2y4Tvj/MnkzNqsbNbfCb5B5KpGX1NZwqIizXDcwZkR0+wQtwSKZp8lyEkqtWAvXQF36OFAZO6c7I3Mr3uBNT6ZJmJFxMd3nZDsLc5qu9dBCO3pMeMvv3vI1EHSS+XV+qPl1u3tAWDnChFpi5GLSrHULJ911qpvNxNQUmfTq8qph5B0PGArD4dk+dyxxBkPvAfp/aTI84YYOQuE7HdE68S/x648xQ8rMh1C/bSezzdFcJjMz5HUJ+Clh2/xxA1vu7ymA+k0vbqxq48fFvUPES3M5Tagj2/6i5X1+orEYlgfZ5Tzl3TuWf8ODH7Bq1PgPXh+RwPBSLrVh9Eb8DiFPEn7fxh/r9xYwPtCaBd9BEhdDDFlLfyudrSRaBc1ddayreNeG9W5571x7VmGyNnp7QAWP+tPQnZViHsQdh5gm/QySU8tFV38oYHDO2xBCXphOusUuYj9vDy9D4kinM39GTK13TilrKDmG2voWepuCbIYlMeAXXDY=
  app: quigleysweb
  on:
    repo: mike-quigley/QuigleysWeb
=======
    secure: M8HElDAespiWuZnNI3gjdnLv6zYVOVngSzi4ZGRmVypFKteUnqcBsv6Qi+6k6FVSbLp/bKg3DwQumQxHGR2LaHNsvCqJumGczTX+cMkR/OBDE3TciViJLnE4JiczQt6D7uEhbt5X5gN3STvqZM3n4LwKGv4nU6u7pyApKnDKkBPpTuuSJkeEGWhzuh9eUYFgNRpSlfTpgGqa+SRuRFTZzEFVTeMXiOD9+NrNtH/rLJFqXsL/iN6APuBKH+oCjpk+pzP7KH7oD7mO8x+YWvUOZPNSEHbLF5dH01OSKdqwaG4sCS8N/vMAJptKSvwKter2PruO+Xw8lI2s784/si5LpqKjrL2QFx+VikoHp0eQMN6i+NvBW/ypwuyF74Csxsq3WBMkODjGx5p337W4zu0pkPR0URj0o46GZKXqh67tkes/3n/Cxm2LrTROaaRwr0eT3uJGKR7MwhpVzLUQY1bvSiTEdbyvi7KIV+o3/OuCfKQsnKxtjxT1roUWE95c2zyE2jci2rONw0TWhJg7PeA4sdBK6m4VLNGhUnUMAUe+e7XbBPm0IJkIu5FvNIbvHo/4Pnz8mKpjLCWQxJrcRmbj1ptI97bkU7c3gq23bPPxOwdu7RBxoMb1dABf+RzHQF43dipUEtjrxG9IJO0TzxVrQ9/Pid/dZEqjA2/6Oj+d2v8=
  app: quigleysweb
  on:
    repo: mike-quigley/QuigleysWeb
>>>>>>> 8de3c33cbd9aad65874baa54b0befc3bd9a06a97
