language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build

deploy:
  provider: heroku
  api_key:
    secure: itGjRpVqr+FLfRO/SyZ+sroUJJxBLmJnqALSqET5S+m6URkPsH1ncpCOP2hOSQdRIIZ9DVAzSFRtGEEvLQOAXMLrmACtBrIpYyAmicoGF08SvkzcqcgTqd434DwBj+IWeL/SzRgJh9CGlXx3Gi4GyzEmUdChe/7s82UQEysnyvijnYam7nImr0IfoOjkDDYoESz3mIFz906nfdtzyWUJzE9CjN9SJ4xcZoLKJeNNWqPkJWs7mLAhfPTnk+lC6ZZK8zueIAQr96HpRkj5p85wOCb1z3AsslZperMHjR42L9vevUAHn5ARJyX7tX57N5qgITFUEFwwXZl1mG3NFkDDN8ObPnQX1qSIFbDShsT8EWhHxnynlzyzCkAeMHPAusoRSOZRd6si0UdrRr6McZbS+Ds9gdJSL/2uYwKGDr8h+LKfzS/LDku85g/JDZGZRe7fOmkzAhJnOmu2JL/XD1BVVkuCkpA3yoOU7/kLail9hvRsPPrKtMia/O/H2S3BqZukht5sm/GR+Rihud12Pelow8/GqZspilq+H2dS1c3og4DT0WgflV4l+JarRSxa4kTSQCkHC7opH6RduJbG6qbdecOOu6QKI273CXCFSvwr6anfK9dU1iZo2xv8puet1eO5wAKzLLhfXIPf3UhS30gNbFbCcdkhd+l5+kAKrh583Uw=
  app: quigleysweb
  on:
    repo: mike-quigley/QuigleysWeb