language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build

deploy:
  provider: heroku
  api_key: A/I4FJK8HFhh0PeYSpYpuuvHyNLhEn+0UdVAnmrAS+WOmkvxLuIV7q1T119WdSdjVudHYjN/lzR3hbSPnZwA939xzTZxxY4FJKK4B0/yRba12KDZMESuBI0LJewvlzzyjUZDYH0q76o8VgjubDXQBVs73ICnsqFWsuRcKXEciGWvhYirX/k4J3MdOg4ShtsCOXa3jdU3o836Q386dPP4CZP4PtpzwmSTwaRnZ8j5M1AiRsnyL4E/ERHOpr/I9MP3S/36ZP6ljv4kWQ+LqTaZCGsxUOrYhtc3YTcUfjhV6vDvIRIXGyNKfOK+Apvt9GWqSYwelRw3NXUYZPxOkZVCDi/J+FR1rxBrZjhRvhqOknRkY/rl9QSyUL8Ojs9eUtJcBnu0HCezs/C7eWyKjwE8nq02s4g5PFGZ0yhT/UTMitVJ9JPsYA2PYyucVHDnOko8Yye4RITUOPaC6pm6c6/X4v66oZiXKNwYp4u8wOc7nq3B9HFZt8i6XeIGocfLuoEGeuG8Tunc2tuon5jA3SwKw82M0YSWZD+2HaPyN0WAucWIQyvcTfY1Pzo3bgvi49k9rEMsEgvrNgKZh5impVbx4N0inCO/djnFbBOxLETTf9/gVkU2ZQfhijUQOTXJYmIsS0cluBmfeNVL3a84GnPKsO/Jvy+nN5Ct2V2ytC+XTbo=
  app: quigleysweb"
