language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: 'TByZKUDB332P2VEYn9hwuw84o5oR6AkLls9nE48fTe/IOko9KuMS1YImXEoxSUL32qbI/pB2yBqBDjV2lRHWg2GvW0i7kckX6dr6AM0vvLcyY3Ez5B97+JxBeNMfLO4b+Po0aSqcp62C82Jdraiu4etl9vctXwLkEKpjOlB2+Gc3IckgxdXmx7h52KFdlzv4k6TQVklTRTT772mAaDfnGIv4lYaE0aACHx44i6dOoEYFc/wcyYTYZcGkFuXBiMuXes7OuFs3eC7tsEH/uWPh0GjYRi34RKqXOv0beepBSi83nPLxRPYF0IS+7I19bkmSkQ/KkSwxzILCC8WROX46Q4ygkV9SnGpx0kOzE9LArKZwnIp0Z7NwVxl2NB8fAFCMCvJtyhLOLVordhf1sV+l9C/wvdbEMgVc73gys1Zsb+lxK/yaMyeQzmkz1wewSC5/Xogokq3wvmeO4/w02CR0ll3ej4vnETEBGeTspkJg53b1KbQI+SpCOoD9AJHIGwcTb0ndmqFhv4OilB1GlmzwAPO7Gh7CXb/hyEq7ptn3CEX7XebqSL8u+Nlem6HyFlXqsw1xv9w8Tb8t6M5FsztpVt8Wk+5qPea+ZZ1/vqr6TzsFZCnlDRY/J02wfPGl3cbXxfDX+tYKmEPmxEW+tfwKWuqQpwB2ksxNzvhihut7epc='
  app: quigleysweb
  on:
    repo: mike-quigley/QuigleysWeb

branches:
  only:
    - master
